[package]
name = "scheduler-adapter"
version = "0.1.0"
edition = "2021"

[dependencies]
bob-core = { path = "../bob-core" }
requests-handler = { path = "../requests-handler" }
tokio = { version = "1", features = ["rt", "sync", "macros"] }
tracing = "0.1"

[dev-dependencies]
tokio = { version = "1", features = ["rt", "sync", "macros", "time"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[lints]
workspace = true
