[package]
name = "bob"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal"] }
bob-core = { path = "../bob-core" }
tracing = "0.1"
async-trait = { workspace = true }
serde = { workspace = true }
figment = { version = "0.10", features = ["toml", "env"] }
nix = { version = "0.29", default-features = false, features = ["user"] }

[lints]
workspace = true

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["fmt"] }
