[package]
name = "admin-rpc"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt", "sync", "net", "signal", "macros"] }
bob-core = { path = "../bob-core" }
tracing = "0.1"
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
