use std::fmt;
use std::path::PathBuf;
use std::str::FromStr;

use serde::{Deserialize, Serialize};

use crate::types::SessionId;

/// The result of a policy evaluation for a request or action.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PolicyVerdict {
    /// Whether the action is permitted.
    pub allow: bool,
    /// Human-readable explanation for the verdict.
    pub reason: Option<String>,
}

/// Stable discriminant for persisted monitoring audit records.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum AuditRecordKind {
    Event,
    Report,
    Verdict,
}

/// Kind-specific payload carried by an [`AuditRecord`].
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "lowercase")]
pub enum AuditRecordPayload {
    Event(ExtensionEventAuditPayload),
    Report(ExternalReportAuditPayload),
    Verdict(PolicyVerdictAuditPayload),
}

/// Canonical audit envelope persisted by monitoring.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuditRecord {
    /// Stable identifier for the audit record.
    pub id: String,
    /// RFC 3339 UTC timestamp when the record was accepted.
    pub timestamp: String,
    /// Stored record kind name (`event`, `report`, `verdict`).
    pub kind: AuditRecordKind,
    /// Optional session correlation when known.
    pub session_id: Option<SessionId>,
    /// Kind-specific record body.
    pub payload: AuditRecordPayload,
}

/// Structured payload for extension event records.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ExtensionEventAuditPayload {
    /// Stable extension event name.
    pub name: String,
    /// Optional short summary generated by bob.
    pub summary: Option<String>,
    /// Optional resolved absolute working directory used for a `periodic`
    /// (scheduled) firing. Omitted for events that have no execution
    /// directory (for example forwarded pi-agent extension events).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resolved_cwd: Option<PathBuf>,
}

/// Structured payload for policy verdict records.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PolicyVerdictAuditPayload {
    /// Whether the action was allowed.
    pub allow: bool,
    /// Optional reason for the verdict.
    pub reason: Option<String>,
}

/// Structured payload for external action reports.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ExternalReportAuditPayload {
    /// Tool or action name reported by the caller.
    pub action: String,
    /// Outcome status for the attempted action.
    pub outcome: ReportOutcome,
    /// Optional session ID when known by the reporting CLI.
    pub session_id: Option<SessionId>,
    /// Optional human-readable summary.
    pub summary: Option<String>,
}

/// Canonical set of report outcome statuses.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ReportOutcome {
    Success,
    Denied,
    Error,
}

/// Filter kinds accepted from CLI/config text for audit tailing.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum AuditFilterKind {
    Events,
    Reports,
    Verdicts,
}

/// Parse error for [`AuditFilterKind`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ParseAuditFilterKindError {
    pub input: String,
}

impl fmt::Display for ParseAuditFilterKindError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "unknown audit filter kind \"{}\"; expected one of: events, reports, verdicts",
            self.input
        )
    }
}

impl std::error::Error for ParseAuditFilterKindError {}

impl FromStr for AuditFilterKind {
    type Err = ParseAuditFilterKindError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "events" => Ok(Self::Events),
            "reports" => Ok(Self::Reports),
            "verdicts" => Ok(Self::Verdicts),
            _ => Err(ParseAuditFilterKindError {
                input: s.to_owned(),
            }),
        }
    }
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::*;

    #[test]
    fn policy_verdict_allow_serde_json_round_trip() {
        let verdict = PolicyVerdict {
            allow: true,
            reason: Some("user has permission".to_owned()),
        };

        let json = serde_json::to_string(&verdict).expect("serialization must succeed");
        let restored: PolicyVerdict =
            serde_json::from_str(&json).expect("deserialization must succeed");

        assert_eq!(verdict.allow, restored.allow);
        assert_eq!(verdict.reason, restored.reason);
    }

    #[test]
    fn audit_record_event_payload_supports_serde_json_round_trip() {
        let record = AuditRecord {
            id: "audit_001".to_owned(),
            timestamp: "2026-05-20T10:00:00Z".to_owned(),
            kind: AuditRecordKind::Event,
            session_id: Some(SessionId::new()),
            payload: AuditRecordPayload::Event(ExtensionEventAuditPayload {
                name: "extension.tool.called".to_owned(),
                summary: Some("tool invoked".to_owned()),
                resolved_cwd: None,
            }),
        };

        assert_audit_record_round_trip(record);
    }

    // AC-3 (T-123): a populated resolved_cwd stays on the existing `event`
    // record kind — no new audit record kind is introduced for scheduled
    // (`periodic`) firings.
    #[test]
    fn audit_record_event_payload_with_resolved_cwd_keeps_event_record_kind() {
        let record = AuditRecord {
            id: "audit_004".to_owned(),
            timestamp: "2026-05-20T10:03:00Z".to_owned(),
            kind: AuditRecordKind::Event,
            session_id: Some(SessionId::new()),
            payload: AuditRecordPayload::Event(ExtensionEventAuditPayload {
                name: "scheduler.job.fired".to_owned(),
                summary: Some("periodic firing".to_owned()),
                resolved_cwd: Some(PathBuf::from("/srv/bob/workspace")),
            }),
        };

        let json = serde_json::to_value(&record).expect("serialization must succeed");
        assert_eq!(
            json["kind"], "event",
            "resolved_cwd must not introduce a new audit record kind"
        );
        assert_eq!(
            json["payload"]["resolved_cwd"], "/srv/bob/workspace",
            "resolved_cwd must be nested in the event payload, got: {json}"
        );

        assert_audit_record_round_trip(record);
    }

    #[test]
    fn audit_record_report_payload_supports_serde_json_round_trip() {
        let record = AuditRecord {
            id: "audit_002".to_owned(),
            timestamp: "2026-05-20T10:01:00Z".to_owned(),
            kind: AuditRecordKind::Report,
            session_id: Some(SessionId::new()),
            payload: AuditRecordPayload::Report(ExternalReportAuditPayload {
                action: "tool.fs.read".to_owned(),
                outcome: ReportOutcome::Success,
                session_id: None,
                summary: Some("read complete".to_owned()),
            }),
        };

        assert_audit_record_round_trip(record);
    }

    #[test]
    fn audit_record_verdict_payload_supports_serde_json_round_trip() {
        let record = AuditRecord {
            id: "audit_003".to_owned(),
            timestamp: "2026-05-20T10:02:00Z".to_owned(),
            kind: AuditRecordKind::Verdict,
            session_id: Some(SessionId::new()),
            payload: AuditRecordPayload::Verdict(PolicyVerdictAuditPayload {
                allow: false,
                reason: Some("policy denied tool call".to_owned()),
            }),
        };

        assert_audit_record_round_trip(record);
    }

    fn assert_audit_record_round_trip(record: AuditRecord) {
        let json = serde_json::to_string(&record).expect("serialization must succeed");
        let restored: AuditRecord =
            serde_json::from_str(&json).expect("deserialization must succeed");

        assert_eq!(record.id, restored.id);
        assert_eq!(record.timestamp, restored.timestamp);
        assert_eq!(record.kind, restored.kind);
        assert_eq!(record.session_id, restored.session_id);
        assert_eq!(record.payload, restored.payload);
    }

    // AC-1 (T-123): resolved_cwd is omitted from serialized output when absent.
    #[test]
    fn extension_event_audit_payload_omits_resolved_cwd_when_absent() {
        let payload = ExtensionEventAuditPayload {
            name: "extension.tool.called".to_owned(),
            summary: None,
            resolved_cwd: None,
        };

        let json = serde_json::to_value(&payload).expect("serialization must succeed");
        assert!(
            !json
                .as_object()
                .expect("payload serializes to an object")
                .contains_key("resolved_cwd"),
            "resolved_cwd must be omitted from serialized output when absent, got: {json}"
        );
    }

    // AC-2 (T-123): older JSONL audit records written before this field existed
    // must still deserialize, defaulting resolved_cwd to None.
    #[test]
    fn extension_event_audit_payload_deserializes_legacy_json_without_resolved_cwd_field() {
        let legacy = json!({
            "name": "extension.tool.called",
            "summary": "tool invoked"
        });

        let payload: ExtensionEventAuditPayload = serde_json::from_value(legacy)
            .expect("legacy payload without resolved_cwd must still deserialize");

        assert_eq!(payload.resolved_cwd, None);
    }

    // AC-1 (T-123): resolved_cwd serializes as the absolute path when present.
    #[test]
    fn extension_event_audit_payload_includes_resolved_cwd_when_present() {
        let payload = ExtensionEventAuditPayload {
            name: "periodic.job.fired".to_owned(),
            summary: Some("scheduled run".to_owned()),
            resolved_cwd: Some(PathBuf::from("/srv/bob/workspace")),
        };

        let json = serde_json::to_value(&payload).expect("serialization must succeed");
        assert_eq!(
            json.get("resolved_cwd").and_then(|v| v.as_str()),
            Some("/srv/bob/workspace"),
            "resolved_cwd must serialize as the absolute path when present, got: {json}"
        );
    }

    #[test]
    fn audit_filter_kind_from_str_accepts_plural_cli_values() {
        assert_eq!(
            AuditFilterKind::from_str("events").expect("events should parse"),
            AuditFilterKind::Events
        );
        assert_eq!(
            AuditFilterKind::from_str("reports").expect("reports should parse"),
            AuditFilterKind::Reports
        );
        assert_eq!(
            AuditFilterKind::from_str("verdicts").expect("verdicts should parse"),
            AuditFilterKind::Verdicts
        );
    }

    #[test]
    fn audit_filter_kind_from_str_rejects_unknown_values() {
        let err = AuditFilterKind::from_str("veredicts")
            .expect_err("unknown filter value should return an error");
        assert_eq!(err.input, "veredicts");
    }

    #[test]
    fn external_report_payload_deserialization_rejects_unknown_metadata_fields() {
        let report = json!({
            "action": "tool.exec",
            "outcome": "success",
            "session_id": null,
            "summary": "ok",
            "metadata": { "unreviewed": true }
        });

        let err = serde_json::from_value::<ExternalReportAuditPayload>(report)
            .expect_err("unknown metadata must fail deserialization");
        assert!(
            err.to_string().contains("unknown field"),
            "expected unknown field error, got: {err}"
        );
    }

    #[test]
    fn audit_record_kinds_and_filter_kinds_support_serde_json_round_trip() {
        let record_kinds = [
            AuditRecordKind::Event,
            AuditRecordKind::Report,
            AuditRecordKind::Verdict,
        ];

        for kind in record_kinds {
            let json = serde_json::to_string(&kind).expect("serialization must succeed");
            let restored: AuditRecordKind =
                serde_json::from_str(&json).expect("deserialization must succeed");
            assert_eq!(kind, restored);
        }

        let filter_kinds = [
            AuditFilterKind::Events,
            AuditFilterKind::Reports,
            AuditFilterKind::Verdicts,
        ];

        for kind in filter_kinds {
            let json = serde_json::to_string(&kind).expect("serialization must succeed");
            let restored: AuditFilterKind =
                serde_json::from_str(&json).expect("deserialization must succeed");
            assert_eq!(kind, restored);
        }
    }
}
