[package]
name = "chat-adapter"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt", "sync", "macros"] }
bob-core = { path = "../bob-core" }
requests-handler = { path = "../requests-handler" }
tracing = "0.1"

[dev-dependencies]
tokio = { version = "1", features = ["rt", "sync", "macros", "time", "test-util"] }

[lints]
workspace = true
